### ISSUE TITLE
Слить заявки по загородной недвижимости в жилую

### ISSUE THREAD

**Issue by greenman777** [greenman777/crmre#10]
Возможно дублирование заявок по жилой и загородной недвижимости, т.к. эти понятия схожи тем, что там одинаковые типы недвижимости, а геолокацию трудно четко квалифицировать, например, дом в Порошино, Ганино - это загородная недвижимость или городская. Квартира в Слободском - какая? Поэтому предлагаю загородную вообще убрать (скрыть), а заявки, находящиеся в ней, и типы недвижимости перенести в жилую.

**Comment by yaterekhov** [comment]
Поставил новую задачу: Модификация типов недвижимости.
