### ISSUE TITLE
Добавить дату последней модификации в таблицы заявок

### ISSUE THREAD

**Issue by greenman777** [greenman777/crmre#11]
В таблицу заявок и новостроек (можно в конце таблицы) поставить дату последней модификации этой записи.

**Comment by greenman777** [comment]
Дата последней модификации вставлена

**Comment by yaterekhov** [comment]
Нужно еще в таблицу новостроек (таблица с новостройками и таблица с планировками).

**Comment by greenman777** [comment]
Сделано
