### ISSUE TITLE
Проблемы с переносом клиентов из резервных в активные

### ISSUE THREAD

**Issue by greenman777** [greenman777/crmre#13]
В таблице контрагентов (клиенты в резерве мои) нажимаем "Сделать клиентом". Из таблички в резерве запись ушла, а в табличку клиентов запись не пришла. Появилась там только после того, как закрыл и открыл все окна. А должна отображаться срезу после переноса.
Актуальность деления на активных и резервных клиентов?

**Comment by yaterekhov** [comment]
Глюк сохраняется.
