### ISSUE TITLE
История взаимодействия с клинтом - в заявках

### ISSUE THREAD

**Issue by yaterekhov** [greenman777/crmre#20]
Историю взаимодействия с клиентом нужно продублировать в заявках. Разместить так же внизу экрана, но только в свернутом виде. Функционал должен работать. Таким образом можно будет вести комменты по работе с клиентом из-под любой его заявки.
Для общих спроса и предложения, кнопок, которые в верхнем главном меню, это делать не надо. Или заблокируй "разворачивание" этой таблички. Делаем только для заявок, ссылки на которые в левом сайдбаре. Для свободных тоже делаем.

**Comment by greenman777** [comment]
История взаимодействия добавлена для заявок
