### ISSUE TITLE
Глюк с клиентами

### ISSUE THREAD

**Issue by yaterekhov** [greenman777/crmre#24]
Дима, только что пользователь Арасланова Наталья создавала клиента. Возник глюк в карточке пои ее сохранении, ошибка сохранения, что в поле серия паспорта нужно проверить количество символов. Хотя там было 4, т.е. все верно. Мы несколько раз перенабивали это поле и нажимали на сохранить. Но ошибка все выходила, пришлось нажать выход.
После перезагрузки компа создали карточку вновь, и на этот раз она сохранилась корректно.
При проверке клиента в Моих клиентах мы увидели много одноименных записей клиентов с разными номерами. Видимо эти копии карточек клиента возникали при некорректном сохранении.
Фото прилагаю. Посмотри логи, в чем дело.
Девушка соседка по парте сказала, что у нее так же было, но эти дубли потом исчезли.
Видимо какая то проблема с клиентами все же существует. Потому что не я один заметил, что клиенты отображаются не сразу. Я сегодня переносил клиента из резерва в активные, он не сразу отобразился. Как будто бы автоматически что то не обновляется при совершении каких либо действий.
Проверь пожалуйста.

**Comment by greenman777** [comment]
Дублирование возможно связано с перезагрузкой сервера. 
- Введено ограничение в самой форме на 4 символа на серию паспорта, т.е. запись с неправильным размером полей просто не будет уходить на сервер.
- в моих клиентах и в моих в резерве теперь запись отображается сразу после добавления.
