### ISSUE TITLE
Право бригадиру переназначить исполнителя заявки

### ISSUE THREAD

**Issue by yaterekhov** [greenman777/crmre#26]
Бригадиру нужно иметь право назначить (т.е. переназначить) исполнителя заявки вместо себя. Сейчас эта операция не доступна. 
Это срочно, потому что новые заявки от оператора поступают бригадиру, и он их перераспределяет среди своих подчиненных.

**Comment by greenman777** [comment]
Добавил для группы "Бригадиры" нужные права Share Orders Sale и Share Orders Buy. необходимо проверить.
