### ISSUE TITLE
Добавить в фильтр заявок "Завершенные сделки за период"

### ISSUE THREAD

**Issue by yaterekhov** [greenman777/crmre#44]
Нужно добавить в фильтр заявок (и спрос и предложение) возможность отфильтровать завершенные заявки по заданному диапазону дат регистраций. Можно установить на вкладку фильтра "служебные" (для предложений). Таким образом появится возможность упорядочить заявки по периодам (как правило, месяцам) закрытия сделок.
Можно назвать "Завершенные сделки за период" с____  по_____

**Comment by greenman777** [comment]
Фильтр для заявок расширен
