### ISSUE TITLE
Модификация отчетов 2. Отчет по KPI.

### ISSUE THREAD

**Issue by yaterekhov** [greenman777/crmre#54]
1) Поставить тычки "По типу" и "По группам" для возможности вывода по-разному. В подитог добавить кроме "Среднее на 1 агента" еще строчку "Итого по группе". 
2) Добавить столбец "Прирост за период от РН"; расположить его перед столбцом "Прирост за период от агента". 
3) Поправить нормы прироста в мес.: заявки - 32, договоры - 16, показы - 64, сделки - 4.  
4) Переделать название в таблице "Сделок за период" на "Закрыто клиентов за период".

**Comment by greenman777** [comment]
Отчет изменен. Просьба проверить
