### ISSUE TITLE
Расширить поле "Цена"

### ISSUE THREAD

**Issue by yaterekhov** [greenman777/crmre#58]
Расширить поле "Цена" еще на 1 знак, т.е до 999 999 999. В заявках на покупку, продажу, фильтре заявки на продажу, Отчете по типам объектов, Отчете по совершенным сделкам. Если имеет место тип, то актуально для коммерческой недвижимости (+готовый бизнес, но он уйдет в карточку комм нед-ти)
Срочность 4

**Comment by greenman777** [comment]
Размер цены изменен.
