### ISSUE TITLE
Карточка клиента должна редактироваться

### ISSUE THREAD

**Issue by yaterekhov** [greenman777/crmre#67]
В заявках во всех категориях и типах "Все в работе" (левый сайтбар) - то, что доступно категории ВМ, оператор, - в таблице заявок при нажатии пиктограммы "Клиент" открывается карточка клиента, но она не имеет возможности корректироваться, т.к. отсутствует кнопка "сохранить". Просьба сделать возможность редактирования.
Каждый раз перезаходить в Клиенты не удобно.
Срочность 7

**Comment by greenman777** [comment]
Исправлено
