### ISSUE TITLE
Не могу удалить или откорректировать комментарий

### ISSUE THREAD

**Issue by yaterekhov** [greenman777/crmre#69]
Не могу удалить или откорректировать комментарий (действие) в Истории взаимодействия с клиентом. Нужно дать возможность для категории пользователей ВМ, оператор.
Срочность 5

**Comment by greenman777** [comment]
Сделал. Если кнопка удаления и редактирования не будут видны, нужно будет поставить около нее галочку в меню "Столбцы" (Action)
