### ISSUE TITLE
Показать по умолчанию в таблицах заявок столбец "Информация о клиенте"

### ISSUE THREAD

**Issue by greenman777** [greenman777/crmre#8]
Показывать по умолчанию в таблицах заявок столбец "Информация о клиенте". Сейчас приходится каждый раз открывать его через функцию столбцы вручную, это не удобно. При этом нужно учесть права на эту информацию. Агенты должны видеть только своих и переданных им клиентов.

**Comment by greenman777** [comment]
В процессе

**Comment by greenman777** [comment]
Исправлено

**Comment by yaterekhov** [comment]
Ок.
