### ISSUE TITLE
Добавить возможность смотреть завершенные заявки по коммерческой, загородной, земле и готовому бизнесу.

### ISSUE THREAD

**Issue by greenman777** [greenman777/crmre#9]
Не найдена возможность смотреть завершенные заявки по коммерческой, загородной, земле и готовому бизнесу. Попробовал через верхние кнопки "Спрос", "Предложение" - нет, там только жилая. То же и по активным заявкам. Таким образом нужно добавить возможность смотреть все категории завершенных. Или добавить категории недвижимости в фильтр, или добавить завершенные заявки в левое меню (там есть только мои завершенные). Первый вариант предпочтительнее.

**Comment by greenman777** [comment]
Возможность добавлена

**Comment by yaterekhov** [comment]
Да. Добавь еще в "Спрос."

**Comment by greenman777** [comment]
Добавил, запрос закрываю.
